#!/data/data/com.termux/files/usr/bin/bash
echo "[*] Downloading NetHunter installer..."
wget -O install-nethunter-termux https://offs.ec/2MceZWr
chmod +x install-nethunter-termux
echo "[*] Running installer..."
./install-nethunter-termux
